name: Build binutils

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Make ci.sh executable
      run: chmod +x ci.sh

    - name: Install dependencies
      run: bash -e ci.sh deps

    - name: Build binutils
      run: bash -e ci.sh binutils

    - name: Create ZIP archive
      run: zip -r binutils.zip install/

    - name: Upload binutils artifact
      uses: actions/upload-artifact@v4
      with:
        name: binutils
        path: binutils.zip

    - name: Create GitHub Release
      if: success()
      uses: softprops/action-gh-release@v2.3.2
      with:
        files: binutils.zip
        tag_name: ${{ github.ref_name }}
