name: Build test

on:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Make ci.sh executable
      run: chmod +x ci.sh

    - name: Install dependencies
      run: bash ci.sh deps

    - name: Build LLVM
      run: bash ci.sh llvm

    - name: Build binutils
      run: bash ci.sh binutils

    - name: Upload LLVM and binutils
      uses: actions/upload-artifact@v4
      with:
        name: llvm-binutils
        path: install/
